# Generated by Django 2.0 on 2020-05-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_userinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='nature',
        ),
        migrations.AddField(
            model_name='word',
            name='nowing',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='past',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='pasted',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
