# Generated by Django 2.0 on 2020-05-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20200510_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
        migrations.RemoveField(
            model_name='word',
            name='created',
        ),
        migrations.RemoveField(
            model_name='word',
            name='updated',
        ),
    ]
