# Generated by Django 2.0 on 2020-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_word_fushu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='fushu',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
