# Generated by Django 2.0 on 2020-05-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0010_auto_20200514_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.WordColumn'),
        ),
    ]
